// ignore_for_file: avoid_print
// Imports the ZBLL and ZBLS algorithms of Tao Yu's Alg Trainer
// (https://github.com/tao-yu/Alg-Trainer, js/alg_list.js, MIT licence),
// keeps only those that check out on this app's cube model, and writes
// lib/core/solver/zb/zbll_cases.dart and zbls_cases.dart:
//
//   curl -o alg_list.js https://raw.githubusercontent.com/tao-yu/Alg-Trainer/master/js/alg_list.js
//   dart run tool/zb/import_zb.dart alg_list.js
//
// The source does not say which case each algorithm is for: the case is
// found by undoing the algorithm on a solved cube.
import 'dart:io';

import 'package:rubik_solver/core/cube/cube_state.dart';
import 'package:rubik_solver/core/cube/cubie_cube.dart';
import 'package:rubik_solver/core/cube/face.dart';
import 'package:rubik_solver/core/cube/move.dart';
import 'package:rubik_solver/core/solver/cfop/f2l_case.dart';
import 'package:rubik_solver/core/solver/cfop/f2l_cases.dart';

final _solved = CubeState.solved();

void main(List<String> args) {
  final source = File(args.single).readAsStringSync();
  final zbll = _entries(_object(source, 'zbll_full'));
  final zbls = _entries(_object(source, 'ZBLS'));

  // ------------------------------------------------------------------ ZBLL
  final zbllOut = <(String, int, String)>[];
  var zbllRejected = 0;
  for (final (subset, algs) in zbll) {
    for (final (i, alg) in algs.indexed) {
      final moves = _firstValid(alg.split('/'), _isZbll);
      if (moves == null) {
        zbllRejected++;
        print('ZBLL $subset #${i + 1} rejected: $alg');
        continue;
      }
      zbllOut.add((subset, i + 1, Move.format(moves)));
    }
  }

  // ------------------------------------------------------------------ ZBLS
  final zblsOut = <(int, int, String)>[];
  var zblsRejected = 0;
  for (final (key, algs) in zbls) {
    var variant = 0;
    for (final alg in algs) {
      if (alg.trim().isEmpty) continue;
      final moves = _firstValid(alg.split('/'), _isZbls);
      if (moves == null) {
        zblsRejected++;
        print('ZBLS $key rejected: $alg');
        continue;
      }
      zblsOut.add((int.parse(key), ++variant, Move.format(moves)));
    }
  }

  _renumberF2l(zblsOut);

  print('ZBLL: ${zbllOut.length} kept, $zbllRejected rejected');
  print('ZBLS: ${zblsOut.length} kept, $zblsRejected rejected');
  _coverage(zbllOut.map((e) => e.$3).toList(), zblsOut.map((e) => e.$3).toList());

  final out = Directory('lib/core/solver/zb')..createSync(recursive: true);
  File('${out.path}/zbll_cases.dart').writeAsStringSync(
    [
      '// GENERATED by tool/zb/import_zb.dart from Tao Yu\'s Alg Trainer',
      '// (github.com/tao-yu/Alg-Trainer, MIT licence). Do not edit by hand.',
      '',
      "import 'zb_case.dart';",
      '',
      '/// ZBLL: the last layer in one algorithm once its edges are oriented.',
      'const zbllCases = [',
      for (final (subset, n, notation) in zbllOut)
        '  ZbCase(\'$subset\', $n, "$notation"),',
      '];',
      '',
    ].join('\n'),
  );
  File('${out.path}/zbls_cases.dart').writeAsStringSync(
    [
      '// GENERATED by tool/zb/import_zb.dart from Tao Yu\'s Alg Trainer',
      '// (github.com/tao-yu/Alg-Trainer, MIT licence). Do not edit by hand.',
      '',
      "import 'zb_case.dart';",
      '',
      '/// ZBLS: the last F2L pair (front-right slot) while orienting the',
      '/// last-layer edges. The subset is the F2L case number.',
      'const zblsCases = [',
      for (final (key, n, notation) in zblsOut)
        '  ZbCase(\'$key\', $n, "$notation"),',
      '];',
      '',
    ].join('\n'),
  );
}

// ----------------------------------------------------------- JS parsing

String _object(String source, String name) {
  final start = source.indexOf('var $name = {');
  if (start < 0) throw StateError('no $name');
  final end = source.indexOf('\n};', start);
  // Commented-out lines are the author's drafts.
  return source
      .substring(source.indexOf('{', start) + 1, end)
      .split('\n')
      .where((line) => !line.trimLeft().startsWith('//'))
      .join('\n');
}

/// `"key": ["alg", 'alg', ...]` pairs, in order.
List<(String, List<String>)> _entries(String body) {
  final result = <(String, List<String>)>[];
  final entry = RegExp(r'''["']([^"']+)["']\s*:\s*\[(.*?)\]\s*,?\s*$''',
      multiLine: true);
  final string = RegExp(r'"([^"]*)"' r"|'([^']*)'");
  for (final m in entry.allMatches(body)) {
    result.add((
      m.group(1)!,
      [for (final s in string.allMatches(m.group(2)!)) s.group(1) ?? s.group(2)!],
    ));
  }
  return result;
}

// ------------------------------------------------------------- notation

final _token = RegExp(r"([URFDLBMESxyzurfdlb])(w?)(\d?)('?)(\d?)");

/// Moves of an algorithm written loosely: parentheses, missing spaces
/// ("R'U"), `R2'`, `R3`, `Rw`, curly quotes. Null if anything is left over.
List<Move>? _parse(String text) {
  final clean = text.replaceAll(RegExp(r'[()\s]'), '').replaceAll('’', "'");
  if (clean.isEmpty) return null;
  final moves = <Move>[];
  var at = 0;
  for (final m in _token.allMatches(clean)) {
    if (m.start != at) return null;
    at = m.end;
    var letter = m.group(1)!;
    if (m.group(2) == 'w') letter = letter.toLowerCase();
    final layer = MoveLayer.fromSymbol(letter);
    if (layer == null) return null;
    final count = int.tryParse(m.group(3)! + m.group(5)!) ?? 1;
    final prime = m.group(4)!.isNotEmpty;
    var turns = count % 4;
    if (prime) turns = (4 - turns) % 4;
    if (turns != 0) moves.add(Move(layer, turns));
  }
  return at == clean.length ? moves : null;
}

List<Move>? _firstValid(
  List<String> alternatives,
  bool Function(List<Move>) valid,
) {
  for (final alt in alternatives) {
    final moves = _parse(alt);
    if (moves != null && moves.isNotEmpty && valid(moves)) return moves;
  }
  return null;
}

// ------------------------------------------------------------- checking

CubieCube _cubie(CubeState s) => CubieCube.fromState(s.withCentersNormalized());

/// The algorithm keeps the white (D) side down: the case, and the cube
/// after it, have D on the bottom.
bool _keepsBottom(List<Move> moves) =>
    _solved.applyAll(moves).center(Face.d) == Face.d;

bool _cornerOk(CubieCube c, int i) => c.cp[i] == i && c.co[i] == 0;

bool _edgeOk(CubieCube c, int i) => c.ep[i] == i && c.eo[i] == 0;

bool _f2lSolved(CubieCube c) =>
    [4, 5, 6, 7].every((i) => _cornerOk(c, i)) &&
    [4, 5, 6, 7, 8, 9, 10, 11].every((i) => _edgeOk(c, i));

bool _edgesOriented(CubieCube c) => [0, 1, 2, 3].every((i) => c.eo[i] == 0);

bool _isZbll(List<Move> moves) {
  if (!_keepsBottom(moves)) return false;
  final c = _cubie(_solved.applyAll(Move.invertSequence(moves)));
  final cornersOriented = [0, 1, 2, 3].every((i) => c.co[i] == 0);
  return _f2lSolved(c) && _edgesOriented(c) && !cornersOriented;
}

bool _isZbls(List<Move> moves) {
  if (!_keepsBottom(moves)) return false;
  final c = _cubie(_solved.applyAll(Move.invertSequence(moves)));
  // The cross and the other three slots are solved; the front-right pair
  // or the edge orientation (or both) are not.
  final rest =
      [5, 6, 7].every((i) => _cornerOk(c, i)) &&
      [4, 5, 6, 7, 9, 10, 11].every((i) => _edgeOk(c, i));
  return rest && !(_f2lSolved(c) && _edgesOriented(c));
}

// ---------------------------------------------------- F2L numbering

/// Where the front-right pair is, the same for cases that differ by a U
/// turn: the smallest of `corner * 24 + edge` over the four U turns.
int _pairClass(CubeState state) {
  var best = 1 << 30;
  for (var u = 0; u < 4; u++) {
    final c = _cubie(state.applyAll(_u(u)));
    final corner = c.cp.indexOf(4), edge = c.ep.indexOf(8);
    final key = (corner * 3 + c.co[corner]) * 24 + edge * 2 + c.eo[edge];
    if (key < best) best = key;
  }
  return best;
}

/// Orders lib/core/solver/cfop/f2l_cases.dart (made by
/// tool/cfop/generate_f2l.dart) by the standard F2L numbering, which the
/// ZBLS set uses: F2L n and ZBLS n-… are then the same pair case.
void _renumberF2l(List<(int, int, String)> zbls) {
  final numberOf = <int, int>{};
  for (final (key, _, notation) in zbls) {
    final pair = _pairClass(
      _solved.applyAll(Move.invertSequence(Move.parseSequence(notation))),
    );
    if (numberOf[pair] case final n? when n != key) {
      throw StateError('ZBLS $key and $n have the same pair case');
    }
    numberOf[pair] = key;
  }
  final numbered = <int, F2lCase>{};
  for (final c in f2lCases) {
    final pair = _pairClass(
      _solved.applyAll(Move.invertSequence(Move.parseSequence(c.notation))),
    );
    final n = numberOf[pair];
    if (n == null || numbered.containsKey(n)) {
      throw StateError('no single standard number for F2L ${c.notation}');
    }
    numbered[n] = c;
  }
  final f2l = File('lib/core/solver/cfop/f2l_cases.dart');
  final lines = f2l.readAsLinesSync();
  final header = lines.takeWhile((l) => !l.startsWith('const f2lCases')).toList();
  f2l.writeAsStringSync(
    [
      ...header.where((l) => !l.startsWith('// Numbered')),
      'const f2lCases = [',
      for (var n = 1; n <= 41; n++)
        '  F2lCase(F2lCategory.${numbered[n]!.category.name}, '
            '"${numbered[n]!.notation}"), // F2L $n',
      '];',
      '',
    ].join('\n'),
  );
  print('F2L: renumbered to the standard numbering');
}

// ------------------------------------------------------------- coverage

List<Move> _u(int t) => t % 4 == 0 ? [] : [Move(MoveLayer.u, t)];

void _coverage(List<String> zbll, List<String> zbls) {
  final zbllMoves = [for (final a in zbll) Move.parseSequence(a)];
  final zblsMoves = [for (final a in zbls) Move.parseSequence(a)];

  // ZBLL: every last layer with oriented edges and not-all-oriented corners.
  var cases = 0, missing = 0;
  for (var c = 0; c < 27; c++) {
    final co = [c % 3, c ~/ 3 % 3, c ~/ 9];
    co.add((6 - co.reduce((a, b) => a + b)) % 3);
    if (co.every((t) => t == 0)) continue;
    for (final cp in _perms([0, 1, 2, 3])) {
      for (final ep in _perms([0, 1, 2, 3])) {
        if (_parity(cp) != _parity(ep)) continue;
        final start = CubieCube(
          cp: [...cp, 4, 5, 6, 7],
          co: [...co, 0, 0, 0, 0],
          ep: [...ep, 4, 5, 6, 7, 8, 9, 10, 11],
          eo: List.filled(12, 0),
        ).toState();
        cases++;
        var found = false;
        for (var a = 0; a < 4 && !found; a++) {
          for (final alg in zbllMoves) {
            final after = start.applyAll([..._u(a), ...alg]);
            if ([0, 1, 2, 3].any((b) => after.applyAll(_u(b)).isSolved)) {
              found = true;
              break;
            }
          }
        }
        if (!found) missing++;
      }
    }
  }
  print('ZBLL coverage: ${cases - missing}/$cases last layers');

  // ZBLS: every front-right pair placement and top-edge orientation.
  cases = 0;
  missing = 0;
  const uCorners = [0, 1, 2, 3, 4], uEdges = [0, 1, 2, 3, 8];
  for (final cs in uCorners) {
    for (var twist = 0; twist < 3; twist++) {
      for (final es in uEdges) {
        for (var flip = 0; flip < 2; flip++) {
          for (var eoBits = 0; eoBits < 16; eoBits++) {
            final start = _lastSlot(cs, twist, es, flip, eoBits);
            if (start == null) continue;
            final c = _cubie(start);
            // A pair already in its slot is not a ZBLS case (the last
            // layer is then solved with OLL and PLL).
            if (_f2lSolved(c)) continue;
            cases++;
            var found = false;
            for (var a = 0; a < 4 && !found; a++) {
              for (final alg in zblsMoves) {
                final after = _cubie(start.applyAll([..._u(a), ...alg]));
                if (_f2lSolved(after) && _edgesOriented(after)) {
                  found = true;
                  break;
                }
              }
            }
            if (!found) missing++;
          }
        }
      }
    }
  }
  print('ZBLS coverage: ${cases - missing}/$cases last-slot states');
}

/// The FR corner in slot [cs] twisted [twist], its edge in [es] flipped
/// [flip], the other top edges flipped by [eoBits]; null if impossible.
CubeState? _lastSlot(int cs, int twist, int es, int flip, int eoBits) {
  final cp = List.generate(8, (i) => i), co = List.filled(8, 0);
  final ep = List.generate(12, (i) => i), eo = List.filled(12, 0);
  const dfr = 4, fr = 8;
  if (cs != dfr) {
    cp[dfr] = cs;
    cp[cs] = dfr;
  }
  co[cs] = twist;
  if (es != fr) {
    ep[fr] = es;
    ep[es] = fr;
  }
  eo[es] = flip;
  for (var i = 0; i < 4; i++) {
    if (i != es) eo[i] = eoBits >> i & 1;
  }
  if (es != fr) eo[fr] = eoBits >> 3 & 1; // the top edge now in the slot
  if (eo.reduce((a, b) => a + b).isOdd) return null;
  // Twist the top corner that went into the slot (or UBR) to compensate.
  final compensate = cs != dfr ? dfr : 3;
  co[compensate] = (co[compensate] + 3 - twist) % 3;
  if ((cs != dfr) != (es != fr)) {
    final a = es == 2 ? 0 : 2, b = es == 3 ? 1 : 3;
    final t = ep[a];
    ep[a] = ep[b];
    ep[b] = t;
  }
  return CubieCube(cp: cp, co: co, ep: ep, eo: eo).toState();
}

List<List<int>> _perms(List<int> items) => items.length <= 1
    ? [items]
    : [
        for (var i = 0; i < items.length; i++)
          for (final rest in _perms([
            ...items.sublist(0, i),
            ...items.sublist(i + 1),
          ]))
            [items[i], ...rest],
      ];

int _parity(List<int> p) {
  var inversions = 0;
  for (var i = 0; i < p.length; i++) {
    for (var j = i + 1; j < p.length; j++) {
      if (p[i] > p[j]) inversions++;
    }
  }
  return inversions % 2;
}
