// GENERATED by tool/cfop/generate_f2l.dart, then ordered by
// tool/zb/import_zb.dart. Do not edit by hand.

import 'f2l_case.dart';

/// One algorithm for each of the 41 F2L cases of the front-right slot,
/// numbered as in the standard F2L chart (ordered by tool/zb/import_zb.dart).
const f2lCases = [
  F2lCase(F2lCategory.bothTop, "R U' R'"), // F2L 1
  F2lCase(F2lCategory.bothTop, "F' U2 F"), // F2L 2
  F2lCase(F2lCategory.bothTop, "F' U' F"), // F2L 3
  F2lCase(F2lCategory.bothTop, "R U R'"), // F2L 4
  F2lCase(F2lCategory.bothTop, "R U R' U2 R U' R'"), // F2L 5
  F2lCase(F2lCategory.bothTop, "R' U' R F R' F' U R"), // F2L 6
  F2lCase(F2lCategory.bothTop, "R U2 R' U2 R U' R'"), // F2L 7
  F2lCase(F2lCategory.bothTop, "F' U2 F U F' U2 F"), // F2L 8
  F2lCase(F2lCategory.bothTop, "R U R' U2 F' U' F"), // F2L 9
  F2lCase(F2lCategory.bothTop, "R U' R' U' R U R'"), // F2L 10
  F2lCase(F2lCategory.bothTop, "R U2 R' U F' U' F"), // F2L 11
  F2lCase(F2lCategory.bothTop, "R' U2 R2 U R2 U R"), // F2L 12
  F2lCase(F2lCategory.bothTop, "F' U F U' F' U' F"), // F2L 13
  F2lCase(F2lCategory.bothTop, "R U' R' U R U R'"), // F2L 14
  F2lCase(F2lCategory.bothTop, "F' U F U2 R U R'"), // F2L 15
  F2lCase(F2lCategory.bothTop, "R U' R' U2 F' U' F"), // F2L 16
  F2lCase(F2lCategory.bothTop, "R U2 R' U' R U R'"), // F2L 17
  F2lCase(F2lCategory.bothTop, "F' U2 F U F' U' F"), // F2L 18
  F2lCase(F2lCategory.bothTop, "R U2 R' U R U' R'"), // F2L 19
  F2lCase(F2lCategory.bothTop, "F' U2 F2 R' F' R"), // F2L 20
  F2lCase(F2lCategory.bothTop, "R U' R' U2 R U R'"), // F2L 21
  F2lCase(F2lCategory.bothTop, "R U R' F' U' F"), // F2L 22
  F2lCase(F2lCategory.bothTop, "R2 U2 R' U' R U' R2"), // F2L 23
  F2lCase(F2lCategory.bothTop, "F U R U' R' F' R U' R'"), // F2L 24
  F2lCase(F2lCategory.cornerInSlot, "F' U2 F U2 R U R'"), // F2L 25
  F2lCase(F2lCategory.cornerInSlot, "R U2 R' U2 F' U' F"), // F2L 26
  F2lCase(F2lCategory.cornerInSlot, "R U' R' U R U' R'"), // F2L 27
  F2lCase(F2lCategory.cornerInSlot, "R U2 R' F' U2 F"), // F2L 28
  F2lCase(F2lCategory.cornerInSlot, "R U' R' F' U' F"), // F2L 29
  F2lCase(F2lCategory.cornerInSlot, "R U R' U' R U R'"), // F2L 30
  F2lCase(F2lCategory.edgeInSlot, "R U' R' F' U2 F"), // F2L 31
  F2lCase(F2lCategory.edgeInSlot, "R2 U R2 U R2 U2 R2"), // F2L 32
  F2lCase(F2lCategory.edgeInSlot, "R U' R' U2 R U' R'"), // F2L 33
  F2lCase(F2lCategory.edgeInSlot, "R U R' U2 R U R'"), // F2L 34
  F2lCase(F2lCategory.edgeInSlot, "R U R' U2 F' U2 F"), // F2L 35
  F2lCase(F2lCategory.edgeInSlot, "F' U' F U' R U R'"), // F2L 36
  F2lCase(F2lCategory.bothInSlot, "R U' R U2 F R2 F' U2 R2"), // F2L 37
  F2lCase(F2lCategory.bothInSlot, "R2 U2 R' U' R U' R' U2 R'"), // F2L 38
  F2lCase(F2lCategory.bothInSlot, "R U2 R U R' U R U2 R2"), // F2L 39
  F2lCase(F2lCategory.bothInSlot, "R F U R U' R' F' U' R'"), // F2L 40
  F2lCase(F2lCategory.bothInSlot, "R U F R U R' U' F' R'"), // F2L 41
];
